version: '3'

networks:
    backend:
        driver: bridge

volumes:
    dbdata:
        driver: local

services:

### Workspace Utilities PHP, Git, Composer, Nodejs Service ##################################
    workspace:
        build: ./workspace
        container_name: resumo_workspace
        restart: unless-stopped
        tty: true
        depends_on: 
            - mysql
        volumes: 
            - ./src:/var/www/
            - ./workspace/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        ports: 
            - "9000:9000"
        networks: 
            - backend

### Nginx Service ##################################
    nginx:
        build: ./nginx
        container_name: resumo_nginx
        restart: unless-stopped
        tty: true
        depends_on: 
            - workspace
        volumes: 
            - ./src:/var/www/
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        ports: 
            - "80:80"
            - "443:443"
        networks: 
            - backend

### MySQL Service  ##################################
    mysql:
        build: ./mysql
        container_name: resumo_mysql
        restart: unless-stopped
        tty: true
        env_file:
            - ./mysql/.env
        volumes:
            -  dbdata:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
            - ./mysql/conf.d/docker.cnf:/etc/mysql/conf.d/docker.cnf
            - ./mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        ports:
            - "3306:3306"
        networks:
            - backend